openapi: '3.0.3'
info:
  title: Katalog API
  version: '1.0'
  description: Katalog API
  contact:
    name: "Andreas"
    url: "https://www.predic8.de"
    email: "maier@predic8.de"
servers:
  - url: https://api.server.test/v1
tags:
  - name: "Shop"
paths:
  /artikel:
    get:
      tags:
        - Shop
      summary: Gebe alle Artikel zurück
      description: Liefert alle Artikel zurück
      operationId: getArtikel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artikel'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artikel'
      tags:
        - Shop
      summary: Füge einen Artikel hinzu
      description: | 
        # Fügt einen Artikel hinzu

        ## Ein Artikel besteht aus:
          - name
          - preis
        
        
        Inline-style: 
        ![alt text](https://miro.medium.com/v2/resize:fit:606/1*9mhEcbqWgKRMGu47Jeh7mQ.png "Logo Title Text 1")

        Colons can be used to align columns.

        | Method        | Are           | Cool  |
        | ------------- |:-------------:| -----:|
        | PUT           | right-aligned | $1600 |
        | POST          |   centered    |   $12 |
        | DELETE        | centered      |   $12 |
        | zebra stripes | are neat      |    $1 |




      operationId: postArtikel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:                
                $ref: '#/components/schemas/Artikel'

  /artikel/{aid}:
    parameters:
      - in: path
        name: aid
        schema:
          type: string
        required: true
        description: Artikel ID
        example: "123456678"
    get:
      tags:
        - Shop
      summary: Gebe einen Artikel zurück
      description: Liefert einen Artikel zurück
      operationId: getArtikelAid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artikel'
    


components:
  schemas:
    Artikel:
      properties:
        name:
          type: string
          maxLength: 50
          minLength: 3
          description: Name des Artikels
          example: Cherry
        preis:
          type: number
          minimum: 0
          description: Preis des Artikels
          example: 3.99
      required:
        - name
        - preis
